select count (*) from TAMPERTOKENS
where STATUSID=21;
15814

select count (*) from TAMPERTOKENS
where STATUSID=21
and TIDSPUNKTUDSTEDT > TO_DATE('2019', 'YYYY');


select PLANLAGTTIDSPUNKTLUKKET from TAMPERTOKENS
where STATUSID=21
and PLANLAGTTIDSPUNKTLUKKET > TO_DATE('2019', 'YYYY');

delete from TAMPERTOKENS


select count(*) from TAMPERTOKENS
where  STATUSID=21;

where TIDSPUNKTUDSTEDT  < TO_DATE('2019', 'YYYY')
and STATUSID=21
;